# Acknowledgements {.unnumbered}


<h3> Authors: </h3>
- Julia Matveeva
- Osma Suominen
- Kati Launis
- Leo Lahti

<h3> Contributors: </h3>
- Jeba Akewak
- Pyry Kantanen
- Teo Dallier
- Elliot Gaudron-Parry

<h3> References: </h3>
A national public sphere? Analyzing the language, location, and form of newspapers in finland, 1771–1917 <br>
Marjanen J, Vaara V, Kanner A, Roivainen H, Mäkelä E, Lahti L & Tolonen M.<br>
Journal of European Periodical Studies 4(1), 2019<br>
Special issue: Digital Approaches Towards Serial Publications<br>
<a href="https://doi.org/10.21825/jeps.v4i1.10483">10.21825/jeps.v4i1.10483</a> | <a href="https://github.com/openresearchlabs/openresearchlabs.github.io/blob/master/content/publication_resources/papers/2019-Marjanen-JEPS.pdf">PDF</a>
<br><br>

Bibliographic data science and the history of the book (c. 1500–1800)<br>
Lahti L, Marjanen J, Roivainen H & Tolonen M.<br>
Cataloging & Classification Quarterly 57(1) Routledge, 2019<br>
Special issue.<br>
<a href="https://doi.org/10.1080/01639374.2018.1543747">10.1080/01639374.2018.1543747</a> | <a href="https://github.com/openresearchlabs/openresearchlabs.github.io/blob/master/content/publication_resources/papers/2019-Lahti-CCQ.pdf">PDF</a>

<h3> Funders: </h3>
- Research Council of Finland DHL-FI project
    - <a href="https://www.aka.fi/en/">Academy of Finland website</a>
    - <a href="https://akareport.aka.fi/ibi_apps/WFServlet?IBIF_ex=x_HakKuvaus2&CLICKED_ON=&HAKNRO1=348946&UILANG=en&YMISTA=AKA&TULOSTE=HTML">Funding decision</a>
    

- FIN-CLARIAH research infrastructure
    - <a href="https://www.kielipankki.fi/organization/fin-clariah/">FIN-CLARIAH website</a>
