---
title: "Types of record"
hide-description: false
description: ""
---

```{r}
#| label = "source-index",
#| include = FALSE
source("init.R")
#source("content_type.R")
```

[MARC: leader/06](https://www.loc.gov/marc/bibliographic/bdleader.html)

## Types of record 

```{r}
#| label = "content_type",
#| echo = FALSE,
#| results = "asis"
x <- top(df.orig, "type_of_record")
tab <- cbind(names(x), unname(x), round(100 * unname(x/nrow(df.orig)), 1))
colnames(tab) <- c("Type of Record", "Documents (n)", "Fraction (%)")
kable(head(tab, 14))
```

<!-- Title count per type of record (note the log10 scale): -->

<!-- ```{r} -->
<!-- #| label = "content_type2", -->
<!-- #| echo = FALSE, -->
<!-- #| message = FALSE, -->
<!-- #| warning = FALSE, -->
<!-- #| fig.width = 11, -->
<!-- #| fig.height = 7 -->
<!-- top_plot(df.orig, "bibliographic_level", ntop = 10, log10 = TRUE) + labs(y = "Entries (n)") -->
<!-- ``` -->

## Bibliographic level 

```{r}
#| label = "content_type3",
#| echo = FALSE,
#| results = "asis"
x <- top(df.orig, "bibliographic_level")
tab <- cbind(names(x), unname(x), round(100 * unname(x/nrow(df.orig)), 1))
colnames(tab) <- c("Bibliographic level", "Documents (n)", "Fraction (%)")
kable(head(tab, 10))
```


<!-- ```{r} -->
<!-- #| label = "content_type4", -->
<!-- #| echo = FALSE, -->
<!-- #| message = FALSE, -->
<!-- #| warning = FALSE, -->
<!-- #| fig.width = 11, -->
<!-- #| fig.height = 7 -->
<!-- top_plot(df.orig, "bibliographic_level", ntop = 20, log10 = TRUE) + labs(y = "Entries (n)") -->
<!-- ``` -->