---
title: "Harmonized Fennica Dataset"
format: html
editor: visual
---

The choice of fields to harmonize is guided by the needs of the [Digital History for Literature in Finland (2022-2026)](https://sites.utu.fi/digital-history-literature-finland/) project funded by the Research Council of Finland. The project aims to use digital collections and methods to significantly expand the prevailing understanding of Finnish literature history.

To access a harmonized Fennica dataset, simply download the **harmonized_fennica.csv** file from the provided link. This dataset includes bibliographic details such as Melinda ID numbers, author name and date information, titles, languages, publication years, publication locations, publishers, content types, bibliographic levels, signum, UDC numbers, genre.

[Download harmonized_fennica.csv](https://a3s.fi/swift/v1/AUTH_3c0ccb602fa24298a6fe3ae224ca022f/fennica-container/output.tables/harmonized_fennica.csv).

Harmonized data is also available for a subset of years 1809-1917:

[Download harmonized_fennica19.csv](https://a3s.fi/swift/v1/AUTH_3c0ccb602fa24298a6fe3ae224ca022f/fennica-container/output.tables/harmonized_fennica19.csv).

For more information contact Julia Matveeva (yulmat\@utu.fi).
