---
title : "Publication frequency"
hide-description: false
description: "Size information"
---

```{r}
#| label = "source-index",
#| include = FALSE
source("init.R")
```

```{r source-publication-frequency, include=FALSE, eval=knit_bookdown}
# publication_frequency field
source("publication_frequency.R")
df <- read.csv("df.preprocessed.csv")
```

# Publication frequency summaries

Publication frequency information is available for `r sum(!is.na(df$publication_frequency_text))` documents (`r round(100*mean(!is.na(df$publication_frequency_text)))`%). The links are invalid if the lists are empty. The (estimated annual) frequencies are converted to plain text according to their closest match in [this table](https://github.com/COMHIS/fennica/blob/master/inst/extdata/frequency_conversions.csv).

[Publication frequency accepted](dataTable/data_table.html?path=../output.tables/publication_frequency_accepted.csv)

[Publication frequency conversions](dataTable/data_table.html?path=../output.tables/publication_frequency_conversion.csv)

[Publication frequency discarded](dataTable/data_table.html?path=../output.tables/publication_frequency_discarded.csv)
