---
title : "Publication time"
hide-description: false
description: "Publication year summaries"
---

```{r}
#| label = "source-index",
#| include = FALSE
source("init.R")
source("publication_time.R")
```

[Publication year conversions for the whole data](dataTable/data_table.html?path=../output.tables/publication_time_conversion.csv)

[Publication year discarded for the whole data](dataTable/data_table.html?path=../output.tables/publication_time_discarded.csv)

[Publication year conversions for years 1809-1917](dataTable/data_table.html?path=../output.tables/publication_time_conversion_19.csv)

[Publication year discarded for years 1809-1917](dataTable/data_table.html?path=../output.tables/publication_time_discarded_19.csv)

Publication years in is available for `r sum(!is.na(df.harmonized$publication_year))` documents (`r round(100*mean(!is.na(df.harmonized$publication_year)))`%). The publication years span is `r paste(range(na.omit(df.harmonized$publication_year)), collapse = "-")`.

```{r}
#| label = "summarypublicationyear",
#| echo = FALSE,
#| message = FALSE,
#| warning = FALSE,
#| fig.width = 8,
#| fig.height = 6
# Title count per decade

df2 <- df %>% group_by(publication_decade) %>% filter(publication_decade < 2010) 
p <- ggplot(df2, aes(publication_decade)) +
     geom_bar() + scale_y_log10() +
     ggtitle("Title count timeline")
print(p)
```
